# action.yml
name: 'Create and upload mender artifact'
description: 'Greet someone and record the time'
inputs:
  software_name:
    description: 'resulting software name'
    required: true
  software_version:
    description: 'resulting software version'
    required: true
  device_type:
    description: 'compatible device type'
    required: true
outputs:
  something:
    description: 'I have no idea!'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.software_name }}
    - ${{ inputs.software_version }}
    - ${{ inputs.device_type }}