# action.yml
name: 'Create mender artifact'
description: 'Greet someone and record the time'
inputs:
  artifact_name:
    description: 'resulting artifact name'
    required: true
  device_type:
    description: 'compatible device type'
    required: true
outputs:
  something:
    description: 'I have no idea!'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.artifact_name }}
    - ${{ inputs.device_type }}