on: [push]

jobs:
  artifactjob:
    runs-on: ubuntu-latest
    name: Build a Mender artifact
    steps:
      - name: Create dummy payload
        id: payload
        run: echo "dummy" > $HOME/payload
      - name: Build and use mender-artifact container
        id: artifact
        uses: theyoctojester/mender-push-artifact@main
        with:
          artifact_name: gha_1
          device_type: device_1
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"