on: [push]

jobs:
  artifactjob:
    runs-on: ubuntu-latest
    name: Build a Mender artifact
    steps:
      - name: Get authentication bearer
        id: auth
        run: |
          export JWT=$(curl -s -X POST -u $MENDER_SERVER_USER:$MENDER_SERVER_PASSWORD $MENDER_SERVER_URI/api/management/v1/useradm/auth/login)
          echo "JWT=$JWT" >> $GITHUB_ENV
        env:
          MENDER_SERVER_URI: ${{ secrets.MENDER_SERVER_URI }}
          MENDER_SERVER_USER: ${{ secrets.MENDER_SERVER_USER }}
          MENDER_SERVER_PASSWORD: ${{ secrets.MENDER_SERVER_PASSWORD }}
      - name: Create dummy payload
        id: payload
        run: |
          mkdir input
          echo "dummy" > input/payload
      - name: Build and use mender-artifact container
        id: artifact
        uses: theyoctojester/mender-push-artifact@main
        with:
          software_name: dummypayload
          software_version: 1.23
          device_type: dummydevice