on: [push]

jobs:
  artifactjob:
    runs-on: ubuntu-latest
    name: Build a Mender artifact
    steps:
      - name: Get authentication bearer
        id: auth
        run: |
          export JWT=$(curl -s -X POST -u $MENDER_SERVER_USER:$MENDER_SERVER_PASSWORD $MENDER_SERVER_URI/api/management/v1/useradm/auth/login)
          env
          echo "JWT=$JWT" >> $GITHUB_ENV
        env:
          MENDER_SERVER_URI: ${{ secrets.MENDER_SERVER_URI }}
          MENDER_SERVER_USER: ${{ secrets.MENDER_SERVER_USER }}
          MENDER_SERVER_PASSWORD: ${{ secrets.MENDER_SERVER_PASSWORD }}
      - name: Create dummy payload
        id: payload
        run: |
          mkdir dist
          echo "dummy" > dist/payload
          pwd
          tree .
          env
      - name: Upload payload
        uses: actions/upload-artifact@v2
        with:
          name: payload
          path: dist/
      - name: Build and use mender-artifact container
        id: artifact
        uses: theyoctojester/mender-push-artifact@main
        with:
          artifact_name: gha_1
          device_type: device_1
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"